apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: dailycs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: omoknooni/dailycs-backend:latest
        envFrom:
        - secretRef:
            name: backend-secret
        ports:
        - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: dailycs
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 8001
    targetPort: 8001
  type: ClusterIP