apiVersion: v1
kind: PersistentVolume
metadata:
  name: dailycs-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/c/User/hyeok/study/dailyCS/mysql-data
  claimRef:
    namespace: dailycs
    name: mysql-dailycs-db-0
