apiVersion: v1
kind: Service
metadata:
  name: dailycs-db
  namespace: dailycs
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  selector:
    app: dailycs-db