apiVersion: v1
kind: Service
metadata:
  name: chromadb-headless
  namespace: dailycs
  labels:
    app: chromadb
spec:
  clusterIP: None           # Headless Service
  selector:
    app: chromadb
  ports:
    - name: http
      port: 8000            # ChromaDB 기본 HTTP 포트
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: chroma-service
  namespace: dailycs
  labels:
    app: chromadb
spec:
  selector:
    app: chromadb
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: ClusterIP
