apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: chromadb
  namespace: dailycs
  labels:
    app: chromadb
spec:
  serviceName: chromadb-headless
  replicas: 1
  selector:
    matchLabels:
      app: chromadb
  template:
    metadata:
      labels:
        app: chromadb
    spec:
      containers:
        - name: chroma
          image: chromadb/chroma:latest
          ports:
            - containerPort: 8000
              name: http
          env:
            - name: CHROMA_SERVER_HTTP_PORT
              value: "8000"         # ChromaDB HTTP 포트 설정
          volumeMounts:
            - name: chroma-data
              mountPath: /chroma
  volumeClaimTemplates:
    - metadata:
        name: chroma-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "dailycs-chroma"
        resources:
          requests:
            storage: 2Gi
